# Generated by Django 3.2.6 on 2021-08-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_site',
            options={'verbose_name': 'body', 'verbose_name_plural': 'bodys'},
        ),
        migrations.AlterModelOptions(
            name='header_site',
            options={'verbose_name': 'header', 'verbose_name_plural': 'headers'},
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_shourt_text1',
            field=models.TextField(verbose_name='text1'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_shourt_text2',
            field=models.TextField(verbose_name='text2'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_shourt_text3',
            field=models.TextField(verbose_name='text3'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_shourt_text4',
            field=models.TextField(verbose_name='text4'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_shourt_text5',
            field=models.TextField(verbose_name='text5'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_shourt_text6',
            field=models.TextField(verbose_name='text6'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_title_text1',
            field=models.CharField(max_length=50, verbose_name='title1'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_title_text2',
            field=models.CharField(max_length=50, verbose_name='title2'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_title_text3',
            field=models.CharField(max_length=50, verbose_name='title3'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_title_text4',
            field=models.CharField(max_length=50, verbose_name='title4'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='about_title_text5',
            field=models.CharField(max_length=50, verbose_name='title5'),
        ),
        migrations.AlterField(
            model_name='about_site',
            name='bout_title_text6',
            field=models.CharField(max_length=50, verbose_name='title6'),
        ),
        migrations.AlterField(
            model_name='header_site',
            name='title_about',
            field=models.TextField(verbose_name='about text'),
        ),
        migrations.AlterField(
            model_name='header_site',
            name='title_background_image',
            field=models.ImageField(upload_to='', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='header_site',
            name='title_image',
            field=models.ImageField(upload_to='', verbose_name='logo image'),
        ),
        migrations.AlterField(
            model_name='header_site',
            name='title_logo',
            field=models.CharField(max_length=20, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='header_site',
            name='title_text',
            field=models.TextField(verbose_name='title text'),
        ),
    ]
