# Generated by Django 3.2.6 on 2021-08-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210822_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='copy_right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_right_text', models.CharField(max_length=30, verbose_name='copy right')),
            ],
        ),
    ]
