# Generated by Django 3.2.6 on 2021-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_atack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_model', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'email atack',
                'verbose_name_plural': 'email atacks',
            },
        ),
        migrations.AlterModelOptions(
            name='sms_bomber',
            options={'verbose_name': 'smsbomber', 'verbose_name_plural': 'smsbombers'},
        ),
    ]
