# Generated by Django 3.2.6 on 2021-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack', '0002_auto_20210824_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='tedad_jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'myapp_city',
            },
        ),
    ]
